M48
; DRILL file {KiCad (6.0.2)} date Mon Jul 18 09:17:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-18T09:17:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X1.3851Y-1.7251
X1.3851Y-2.0401
X1.3866Y-2.715
X1.3866Y-3.0299
T0
M30
